version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    env:
    - CGO_ENABLED=0
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'README'
release:
  # Mark the release as not ready for production if there is an indicator for this in the tag e.g. v1.0.0-rc1
  prerelease: auto
publishers:
  - name: save-release-url
    cmd: sh -c "echo '{{ .ReleaseURL }}' > dist/release-url.txt"
